// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateThumbnails implements pgx.CopyFromSource.
type iteratorForCreateThumbnails struct {
	rows                 []CreateThumbnailsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateThumbnails) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateThumbnails) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Url,
		r.rows[0].Type,
		r.rows[0].Width,
		r.rows[0].Height,
		r.rows[0].YoutubeVideoID,
	}, nil
}

func (r iteratorForCreateThumbnails) Err() error {
	return nil
}

func (q *Queries) CreateThumbnails(ctx context.Context, arg []CreateThumbnailsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"thumbnails"}, []string{"url", "type", "width", "height", "youtube_video_id"}, &iteratorForCreateThumbnails{rows: arg})
}
